---
- hosts: all
  become: yes # i.e. become root for running tasks
  gather_facts: false
  pre_tasks:
  - name: Install python2 for Ansible
    raw: bash -c "test -e /usr/bin/python || (apt -qqy update && apt install -qqy python-minimal)"
    register: output
    changed_when: output.stdout != ""
  - name: Gathering Facts
    setup:

  handlers:
    - name: restart apache
      service: name=apache2 state=restarted

#  roles:
#    - apache

  tasks:
    - name: Install Apache
      apt: name=apache2 state=latest

    - name: Start Apache and enable at boot
      service: name=apache2 state=started enabled=yes

    - name: Configure Apache to serve /vagrant/public by default
      template:
          src: provision/000-default.conf
          dest: /etc/apache2/sites-available
          owner: root
          group: root
          mode: 0644
      notify:
          - restart apache
